// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzsamzvhmoiklmzcriim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6c2FtenZobW9pa2xtemNyaWltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2ODE3NTIsImV4cCI6MjA2OTI1Nzc1Mn0.u5OrILLUMuMr-mdS-s7hQulhALZgKIHZA24_fDLGiI8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});